include:
  - ../postgres/docker-compose.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://desafio-cvlb-db-1:5432/todo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: # Por favor colocar a mesma senha que colocou no banco postgres
    restart: unless-stopped
    depends_on:
      - db
