services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://projeto-db-1:5432/todo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: B3wFz3hEg0Uu
    networks:
      - projeto_default
    restart: unless-stopped

networks:
  projeto_default:
    external: true
