services:
  vite:
    build: .
    container_name: todo-front
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
    depends_on:
      - app
